### ISSUE TITLE
Crash on launch.

### ISSUE THREAD

**Issue by Sunekaer** [chylex/Minecraft-Window-Title#1] opened 2020-03-07 13:10 UTC
Crash doesnt happen very time, its quiet rare it happens

https://hastebin.com/kabureceso.rb

1.15.2-forge-31.1.18
customwindowtitle-1.15.2-v1.0.0

**Comment by chylex** [comment] 2020-03-07 17:49
Reproduce the crash without the 150 other mods.

**Comment by chylex** [comment] 2020-04-15 06:57
Any updates on this? Nothing in the log points to CWT as the cause of the crash, so I'll close the issue unless you actually reproduced the crash with just Forge and CWT.

**Closed** 2020-06-26 12:45 UTC
