### ISSUE TITLE
No support for icons in 1.21

### ISSUE THREAD

**Issue by sheduxdev** [chylex/Minecraft-Window-Title#13] opened 2024-07-20 15:05 UTC
I configurated the mod and it still doesnt change the icons of game.
![image](https://github.com/user-attachments/assets/e3bb655f-3246-48d1-b25e-7535db9714ae)
![image](https://github.com/user-attachments/assets/f769f395-d666-4c6a-84c1-dd666d194333)

**Comment by chylex** [comment] 2024-07-20 16:18
Duplicate of #9.

**Closed by chylex** 2024-07-20 16:18 UTC
